# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: ubuntu-latest

jobs:
- job: InstallNode
  displayName: 'Install Node.js'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.16.0'

- job: RunNpmCi
  displayName: 'npm ci'
  dependsOn: InstallNode
  steps:
    - script: |
        npm ci
      workingDirectory: $(Build.SourcesDirectory)

- job: RUN
  displayName: 'npm run'
  dependsOn: RunNpmCi
  steps:
    - script: |
        npx cypress run --e2e --browser chrome
      workingDirectory: $(Build.SourcesDirectory)

- job: GenerateReport
  displayName: 'Generate Report'
  dependsOn: RunNpmCi
  steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'cypress/reports/html'
        ArtifactName: 'CypressHTMLReports'
        publishLocation: 'Container'