# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
version: 1.2

parameters:
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest
- name: navegador
  displayName: Navegadores
  type: string
  default: chrome
  values:
  - chrome
  - firefox
  - edge
  - electron
- name: tags
  displayName: Tags
  type: string
  default: "@regresion"

trigger:
- none

jobs:
- job: vm
  displayName: vmImage
  pool:
    vmImage: ${{ parameters.image }}
- job: InstallNode
  displayName: 'Install Node.js'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.16.0'

- job: RunNpmCi
  displayName: 'npm ci'
  dependsOn: InstallNode
  steps:
    - script: |
        npm ci
        npx cypress run --e2e --browser ${{ parameters.navegador }} --env grepTags=${{ parameters.tags }}

- job: GenerateReport
  displayName: 'Generate Report'
  dependsOn: RunNpmCi
  steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'cypress/reports/html'
        ArtifactName: 'CypressHTMLReports'
        publishLocation: 'Container'