name: complete e2e

on:
  push:
    branches:
      'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4.1.1

      - name: install npm
        run: npm ci

      - name: run unit tests
        run: npx jest jestUnitTests/asyUncExample.test.js
