name: complete e2e

on:
  push:
    branches:
      'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4.1.1

      - name: install npm
        run: npm ci

      - name: run unit tests
        run: npx jest

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
  
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
        # CodeQL supports ['cpp','csharp','go','java','javascript','python','ruby']
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language ${{matrix.language}}"

  cleanup:
      needs: [build]
      runs-on: ubuntu-latest
      environment: Testing
  
      steps:
        - name: "cleanup destination"
          run: |
            echo "repository variable: $USER_TEST"
          env:
            USER_VAR: ${{ vars.USER_TEST }}
            PASS_SECRET: ${{ secrets.PASS_TEST }}
  
  e2e:
      needs: [cleanup]
      runs-on: ubuntu-latest
      environment: Testing
  
      steps: 
        - name: Checkout
          uses: actions/checkout@v4.1.1
  
        - name: install npm
          run: npm ci
          
        - name: run tests de cypress
          run: npx cypress run --e2e --browser chrome
      
        - uses: actions/download-artifact@v4.0.0
          with:
            name: my_new_report.html
            path: ./reports/my_new_report.html

