name: complete e2e

on:
  push:
    branches:
      'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4.1.1

      - name: install npm
        run: npm ci

      - name: run unit tests
        run: npx jest jestUnitTests/asyUncExample.test.js

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
  
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
        # CodeQL supports ['cpp','csharp','go','java','javascript','python','ruby']
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      
    - name: Initialize CodeQL
      uses: advanced-security/codeql-bundle-action@v1.1.0
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "language ${{matrix.language}}"