name: Ejecuta el workflow solo si hay un PR que comience con el id de Jira

on:
  pull_request:
    types: ['opened','edited','reopened','synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: seferov/pr-lint-action@v1.2.0
      with:
        title-regex: '^\JIRA-\d+\s.+'
        error-message: 'Add ticket ID to your title e.g. "JIRA-1"'
